# Dockerfile.release

FROM elixir:1.4.2
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app
COPY ./dummy_app.tar.gz ./
RUN tar xfz dummy_app.tar.gz

ENTRYPOINT ["bin/dummy_app"]
